default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: my_task_development
test:
  <<: *default
  database: my_task_test
production:
  <<: *default
  database: my_task_production
  username: my_task
  password: <%= ENV['MY_TASK_DATABASE_PASSWORD'] %>
